import{CONFIG}from"./config.js";import{state}from"./state.js";import{startCamera,stopCamera,videoElement}from"./camera.js";import{identify,loadModel}from"./classifier.js";import{connect,sendCommand,signal,supported}from"./serial.js";import{cameraControls,clearResult,message,renderCards,showPrediction,showPriorities,confirmPriority,status}from"./ui.js";import{installButton,register}from"./pwa.js";
const start=document.getElementById('startButton'),identifyButton=document.getElementById('identifyButton'),stop=document.getElementById('stopButton'),connectButton=document.getElementById('connectButton'),defaultTerrainButton=document.getElementById('defaultTerrainButton'),reveal=document.getElementById('revealButton'),confirm=document.getElementById('confirmPriority');
async function begin(){start.disabled=true;clearResult('Preparing camera');try{await loadModel();await startCamera();message('')}catch(error){message(error.message);start.disabled=false}}
export async function activateScenario(prediction){state.setPrediction(prediction);showPrediction(prediction);const sent=await signal(prediction);const source=prediction.source==='manual'?'Manual backup':'GTM';message(sent?`${source} scenario sent to Arduino over USB.`:`${source} scenario active. Arduino is not connected.`)}
async function classify(){identifyButton.disabled=true;clearResult('AI is identifying the scenario');try{const prediction=await identify(videoElement());await activateScenario({...prediction,source:'gtm'})}catch(error){message(error.message);clearResult('Prediction unavailable')}finally{identifyButton.disabled=false}}
async function activateManual(event){const button=event.currentTarget;const index=Number(button.dataset.manualScenario);button.disabled=true;try{await activateScenario({index,confidence:null,source:'manual'})}finally{button.disabled=false}}
function end(){stopCamera();state.clearPrediction();clearResult('Camera stopped')}
async function connectUno(){connectButton.disabled=true;try{await connect();message('Arduino connected. Ready for S1–S6.')}catch(error){message(error.message)}finally{connectButton.disabled=false}}
function revealPriorities(){if(state.prediction)showPriorities(state.prediction)}
function lockPriority(){if(state.prediction)confirmPriority(state.prediction)}
async function showDefaultTerrain(){const sent=await sendCommand('D');message(sent?'Default terrain sent to Arduino.':'Connect Arduino first to show default terrain.')}
function boot(){renderCards();cameraControls(false);clearResult();status('model','Not loaded');status('camera','Not started');status('serial','Not connected');if(!supported()){connectButton.disabled=true;message('Web Serial needs Chrome or Edge on desktop.')}installButton();register()}
start.addEventListener('click',begin);defaultTerrainButton.addEventListener('click',showDefaultTerrain);identifyButton.addEventListener('click',classify);stop.addEventListener('click',end);connectButton.addEventListener('click',connectUno);reveal.addEventListener('click',revealPriorities);confirm.addEventListener('click',lockPriority);document.querySelectorAll('[data-manual-scenario]').forEach(button=>button.addEventListener('click',activateManual));boot();
