import{CONFIG}from"./config.js";
const $=id=>document.getElementById(id);
const el={cameraStatus:$('cameraStatus'),modelStatus:$('modelStatus'),serialStatus:$('serialStatus'),camera:$('camera'),placeholder:$('cameraPlaceholder'),start:$('startButton'),identify:$('identifyButton'),stop:$('stopButton'),message:$('message'),predictionTitle:$('predictionTitle'),predictionDetail:$('predictionDetail'),confidence:$('confidence'),cascadePanel:$('cascadePanel'),cascadeList:$('cascadeList'),hazardPanel:$('hazardPanel'),hazardText:$('hazardText'),context:$('contextPanel'),contextTitle:$('contextTitle'),contextSummary:$('contextSummary'),reveal:$('revealButton'),priorities:$('prioritiesPanel'),list:$('prioritiesList'),priorityChoices:$('priorityChoices'),choiceStatus:$('choiceStatus'),confirmPriority:$('confirmPriority'),cards:$('scenarioCards')};
export function status(name,text,tone='neutral'){const node=el[`${name}Status`];node.textContent=text;node.dataset.tone=tone}
export function message(text=''){el.message.textContent=text}
export function cameraControls(on){el.start.disabled=on;el.identify.disabled=!on;el.stop.disabled=!on;el.placeholder.hidden=on}
export function clearResult(text='Awaiting camera'){el.predictionTitle.textContent=text;el.predictionDetail.textContent='Start the camera, place a scenario in view, and select Identify scenario.';el.confidence.textContent='Confidence —';el.cascadePanel.classList.add('hidden');el.hazardPanel.classList.add('hidden');el.context.classList.add('hidden');el.priorities.classList.add('hidden');el.reveal.disabled=true;el.confirmPriority.disabled=true;el.choiceStatus.textContent='';document.querySelectorAll('.card').forEach(card=>card.classList.remove('active'))}
export function renderCards(){CONFIG.SCENARIOS.forEach((scenario,index)=>{const card=document.createElement('article');card.className='card';card.dataset.index=index;card.innerHTML=`<p class="eyebrow">Scenario ${index+1}</p><h3>${scenario.title}</h3><p>${scenario.context}</p>`;el.cards.append(card)})}
export function showPrediction(prediction){const scenario=CONFIG.SCENARIOS[prediction.index];el.predictionTitle.textContent=scenario.title;el.predictionDetail.textContent=`AI identified ${scenario.modelLabel}. ${scenario.summary}`;el.confidence.textContent=`Confidence ${(prediction.confidence*100).toFixed(1)}%`;el.cascadeList.replaceChildren(...scenario.cascade.map((step,index)=>{const item=document.createElement('li');item.innerHTML=`<span>${index+1}</span><strong>${step}</strong>`;return item}));el.cascadePanel.classList.remove('hidden');el.hazardText.textContent=scenario.hazard;el.hazardPanel.classList.remove('hidden');el.contextTitle.textContent=`Context ${prediction.index+1}`;el.contextSummary.textContent=scenario.context;el.context.classList.remove('hidden');el.priorities.classList.add('hidden');el.reveal.disabled=false;el.choiceStatus.textContent='';el.confirmPriority.disabled=true;document.querySelectorAll('.card').forEach(card=>card.classList.toggle('active',Number(card.dataset.index)===prediction.index))}
export function showPriorities(prediction){const scenario=CONFIG.SCENARIOS[prediction.index];el.list.replaceChildren(...scenario.priorities.map(priority=>{const item=document.createElement('li');item.textContent=priority;return item}));el.priorityChoices.replaceChildren(...scenario.choices.map((choice,index)=>{const label=document.createElement('label');label.className='priority-choice';label.innerHTML=`<input type="radio" name="humanPriority" value="${index}"><span><strong>Priority ${index+1}</strong>${choice}</span>`;return label}));el.priorities.classList.remove('hidden');el.choiceStatus.textContent='Select the action you would prioritize.';el.confirmPriority.disabled=true;document.querySelectorAll('input[name="humanPriority"]').forEach(input=>input.addEventListener('change',()=>{el.confirmPriority.disabled=false;el.choiceStatus.textContent='Priority selected. Confirm your decision.'}))}
export function confirmPriority(prediction){const selected=document.querySelector('input[name="humanPriority"]:checked');if(!selected)return;const scenario=CONFIG.SCENARIOS[prediction.index];const choice=scenario.choices[Number(selected.value)];el.choiceStatus.textContent=`Human priority locked: ${choice}`;el.confirmPriority.disabled=true;document.querySelectorAll('input[name="humanPriority"]').forEach(input=>input.disabled=true)}
